apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: etcdoc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: etcdoc
  template:
    metadata:
      labels:
        app: etcdoc
    spec:
      hostNetwork: true
      serviceAccountName: {{ .Values.serviceAccount.name }}
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      initContainers:
      - name: install-logrotate
        image: busybox
        command:
        - sh
        - -c
        - |
          mkdir -p /host/etc/logrotate.d
          cat <<EOF > /host/etc/logrotate.d/etcdoc
          /var/lib/rancher/rke2/server/tls/etcd/etcdoc-diag.log {
              size 50M
              rotate 5
              compress
              missingok
              notifempty
              copytruncate
          }
          EOF
        volumeMounts:
        - name: logrotate-conf
          mountPath: /host/etc/logrotate.d
      containers:
      - name: etcdoc
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["-config", "/etc/tool/config.yaml"]
        ports:
        - name: http
          containerPort: {{ .Values.config.observability.metrics_port }}
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: false
          runAsUser: 0
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: config
          mountPath: /etc/tool
          readOnly: true
        - name: etcd-certs
          mountPath: /etc/etcd
          readOnly: true
        - name: etcd-logs
          mountPath: /var/lib/rancher/rke2/server/tls/etcd/
          readOnly: false
      volumes:
      - name: config
        configMap:
          name: etcdoc-config
      - name: etcd-certs
        hostPath:
          path: /var/lib/rancher/rke2/server/tls/etcd/
          type: Directory
      - name: etcd-logs
        hostPath:
          path: /var/lib/rancher/rke2/server/tls/etcd/
          type: DirectoryOrCreate
      - name: logrotate-conf
        hostPath:
          path: /etc/logrotate.d/
          type: DirectoryOrCreate
