apiVersion: v1
kind: Service
metadata:
  name: etcdoc
  namespace: {{ .Release.Namespace }}
  labels:
    app: etcdoc
spec:
  selector:
    app: etcdoc
  ports:
  - name: http
    port: {{ .Values.config.observability.metrics_port }}
    targetPort: {{ .Values.config.observability.metrics_port }}
